runtime: python39  # Specify the Python runtime version

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app  # Your application's entry point


# App Engine features and scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65  # Adjust as needed
  min_instances: 1
  max_instances: 10

# Resource settings (memory, CPU, etc.)
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Handlers section for routing requests to your app (you may need to customize this)
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

# Service and version settings
service: my-service
version: v1
